/* AutoMod global definition file */

#ifndef __DECLS_H__
#define __DECLS_H__

#include "user.h"
struct model_agv1_struct {
	System* $sys;
	Path* am_caminho9;
	Path* am_caminho8;
	LocHead* am_cp_Saisa;
	Path* am_caminho12;
	LocHead* am_cp_Maq2;
	LocHead* am_cp_Maq1;
	LocHead* am_cp_Entrada;
	Path* am_caminho10;
	Path* am_caminho4;
	Path* am_caminho11;
	Path* am_caminho3;
	LocHead* am_cp_Maq3;
	Path* am_caminho7;
	Path* am_caminho6;
	VehType* am_DefVehicle;
	LocHead* am_cp_Park;
	System* am_parentsys;
	LocHead* am_cpStart;
	Path* am_caminho2;
	Path* am_caminho1;
};
struct model_conv_struct {
	System* $sys;
	ConvSectionType* am_DefaultSection;
	ConvStationType* am_DefaultStation;
	ConvPhotoeyeType* am_DefaultPhotoeye;
	ConvMotorType* am_DefaultMotor;
	ConvTransferType* am_DefaultTransfer;
	System* am_parentsys;
};
char* Acceleration_valstrfunc(void*);
char* BlockPtr_valstrfunc(void*);
char* BlockList_valstrfunc(void*);
char* Color_valstrfunc(void*);
char* CounterPtr_valstrfunc(void*);
char* Distance_valstrfunc(void*);
char* FilePtr_valstrfunc(void*);
char* GraphPtr_valstrfunc(void*);
char* Integer_valstrfunc(void*);
char* LabelPtr_valstrfunc(void*);
char* LoadPtr_valstrfunc(void*);
char* LoadList_valstrfunc(void*);
char* LoadTypePtr_valstrfunc(void*);
char* Location_valstrfunc(void*);
char* LocationList_valstrfunc(void*);
char* MaterialPtr_valstrfunc(void*);
char* MonitorPtr_valstrfunc(void*);
char* MotorPtr_valstrfunc(void*);
char* OrderListPtr_valstrfunc(void*);
char* PathPtr_valstrfunc(void*);
char* PathList_valstrfunc(void*);
char* PhotoeyePtr_valstrfunc(void*);
char* PipePtr_valstrfunc(void*);
char* ProcessPtr_valstrfunc(void*);
char* QueuePtr_valstrfunc(void*);
char* Rate_valstrfunc(void*);
char* Real_valstrfunc(void*);
char* ResourcePtr_valstrfunc(void*);
char* SchedJobPtr_valstrfunc(void*);
char* SchedJobList_valstrfunc(void*);
char* SectionPtr_valstrfunc(void*);
char* StatePtr_valstrfunc(void*);
char* StreamPtr_valstrfunc(void*);
char* String_valstrfunc(void*);
char* StringList_valstrfunc(void*);
char* SystemPtr_valstrfunc(void*);
char* TablePtr_valstrfunc(void*);
char* TankPtr_valstrfunc(void*);
char* TankTransferPtr_valstrfunc(void*);
char* TankTransferList_valstrfunc(void*);
char* TankTriggerPtr_valstrfunc(void*);
char* TankTriggerList_valstrfunc(void*);
char* Time_valstrfunc(void*);
char* TransferPtr_valstrfunc(void*);
char* VehiclePtr_valstrfunc(void*);
char* VehicleList_valstrfunc(void*);
char* Velocity_valstrfunc(void*);
struct model_struct {
	System* $sys;
	process* am_die;
	variable* am_Flag_reserva_M3$var;
	int32 am_Flag_reserva_M3;
	process* am_P_P3;
	process* am_P_P1;
	process* am_P_P2;
	queue* am_q2;
	queue* am_q1;
	queue* am_q3;
	queue* am_qE_Maq3;
	rnstream* am_stream_r_Maquina1_1;
	process* am_P_configuracao;
	variable* am_OPCTimestamp$var;
	char* am_OPCTimestamp;
	struct model_agv1_struct am_agv1;
	rnstream* am_stream_r_Maquina3_1;
	attribute* am_t_P3M2$att;
	rnstream* am_stream_r_Maquina2_1;
	attribute* am_t_P3M3$att;
	variable* am_Flag_reserva_M2$var;
	int32 am_Flag_reserva_M2;
	attribute* am_t_P2M3$att;
	attribute* am_t_P1M2$att;
	variable* am_Flag_reserva_M1$var;
	int32 am_Flag_reserva_M1;
	System* am_modelsys;
	attribute* am_t_P1M1$att;
	queue* am_Space;
	attribute* am_t_P2M1$att;
	loadtype* am_L_p2;
	loadtype* am_L_incial;
	loadtype* am_L_p1;
	rnstream* am_stream0;
	queue* am_QE;
	loadtype* am_L_p3;
	queue* am_QF;
	queue* am_qE_Maq2;
	struct model_conv_struct am_conv;
	queue* am_qE_Maq1;
	resource* am_r_Maquina3;
	variable* am_OPCQuality$var;
	int32 am_OPCQuality;
	resource* am_r_Maquina2;
	resource* am_r_Maquina1;
	rnstream* am_stream_L_incial_1;
};
extern struct model_struct am_model;
void initglobs0();
#endif /* __DECLS_H__ */
